# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  profiles: 
    active: druid
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

#日志输出执行的sql语句
logging:
  level:
    com.study.mybatisplus.mapper: DEBUG
  file:
    path: ./.log #可以指定文件生成的路径（可以是绝对路径也可以是相对路径。./代表当前目录），与name只能生效一个
#    name: mylog.log #直接在根目录下创建文件
#核心日志开启debug日志级别，将自动配置相关的日志输出到控制台
#trace: true
#debug: true
